### PR TITLE
Adds article about simulation

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
## Motivation

A few eons ago, we had a discussion about simulation. I wrote about it (and re-did most of the text several times). 

## Approach

Simulation is such a vast topic, and in the discussion many more points were touched. However, I'm limiting this article to the scope of team decoupling. I'm not diving much into the technical details about simulation, for the concept itself needs to be introduced first. 

Follow up articles can be more technical, or focus on other aspects of simulation (testing, for instance). 

[Rendered version](https://deploy-preview-92--frontside.netlify.app/blog/2020-07-29-decoupling-teams-through-simulation/)

### CODE REVIEW

**Comment by cowboyd** [comment]
This is really good. Are there more edits coming?

**Comment by taras** [comment]
@cowboyd are you expecting more edits?

**Comment by cowboyd** [comment]
> @cowboyd are you expecting more edits?

I'm not, but I have a vague notion that I saw @jorgelainfiesta mention that more were coming... I'm good with this as-is, but just want to know if I should keep a heads up for another version.

**Comment by jorgelainfiesta** [comment]
@cowboyd  nope, I submit article PRs only after they are fully done (post editor, post adding graphics, etc).

**Comment by cowboyd** [comment]
> @cowboyd  nope, I submit article PRs only after they are fully done (post editor, post adding graphics, etc). 

Jorge does not get up on the stage unless he's ready to flex. 😁

**Comment by jorgelainfiesta** [comment]
haha in the first articles there was some back peddling for submitting not fully ready things. Now I feel more confident about what I write so I don't ask around for opinions as much as before, specially because everybody's already too busy

**Pull request merged**
