### PR TITLE
Rearrange metadata into layout and include Twitter card

### PR DESCRIPTION
**Pull request by minkimcello**
## Motivation
_Disclaimer: I say metadata a lot in this pull request._

The metadata for blog posts were not implemented correctly so it was defaulting to the overall site metadata. This meant that when you share a blog post, the description in the preview would be the description of Frontside and not the description of the blog post. And while fixing this I thought I might as well refactor all the other pages with the new metadata layout too.

### Normal metadata
The blog posts' metadata was being passed into the `blog-post` template as a prop but wasn't actually being utilized so I brought it up one level (while still in the blog template) which fixed the issue. But while refactoring the other templates, I thought it would be tidier by allowing the `layout` component to accept `title` and `description` props (as opposed to importing `Helmet` to each template that needs it) so that templates can simply choose to either use its own title/description or have it default to the site's title/description.

The format in which this works is if you pass in a title prop, the metadata for that page will be generated as `${prop.title} | Frontside`, and if no title is passed in it'll just be `Frontside`.

Update: 
  - And if you're navigating past the first page of `Blog`, it'll be displayed as `Blog - page x | Frontside`. Did not have to do this for `Podcast` because it doesn't generate pages.

### Image metadata
The Frontside logo has also been added to the site's metadata. So on iMessage it looks like this:

Screen Shot 2020-04-07 at 2 10 41 PM

### Twitter metadata
I've given it the same treatment for Twitter's meta tags (in `layout`) where it just borrows the same argument from the site's metadata:

Screen Shot 2020-04-07 at 6 11 34 PM

### Blog Image metadata
Per @jorgelainfiesta's suggestion I changed the `blog-post` template to be able to pass image, when available, into the metadata. The current blog post markdown formats have been following the pattern of using `image` as one of its field but it wasn't actually being used anywhere and I couldn't use it as it was returning its relative path as processed by the `gatsby-source-filesystem` plugin. When we use `img` instead, `gatsby-remark-images` gives us access to a wider variety of queries, as well as allow us to query up a smaller res of images, which makes it easier to pass the image into the `helmet`.

Notes:
  - If a blog post does not have an `img` then it'll use the Frontside logo as default.
  - I've changed all the `images` to `img` for every blog post markdown file.
    - Not important but I also rearranged all the fields of those blog post files so that they follow the same order (`templatekey`, `title`, `date`, `author`, `description`, `tags`, and then `image`).
  - Some blog posts were using a link for its `image` field so I downloaded the images and stored them locally.

## TODO?
- [x] Update the following templates:
  - [x] About
  - [x] Contact
  - [x] Services
  - [x] Podcast
    - [x] [Episodes]
  - [x] Blog
    - [x] [Posts]
  - [x] People
    - [x] [Persons]
  - [x] Tag
    - [x] [Tags]
- [x] Update Frontside logo file?
  - @jorgelainfiesta Is there a cleaner version of the Frontside logo? See image above with the white specks around the logo on Twitter.
- [ ] ⚠️ Do we need `directory_index`, `published`, `cta_text`, and or `cta_button` fields for our blog post markdowns? They seem to be from a previous iteration of the website and I can't find it being utilized anywhere unless it's something integrated with Netlify? ⚠️

### CODE REVIEW

**Comment by jorgelainfiesta** [comment]
Can we make it possible to pass an optional image to the metadata? For instance, in the blog post I'd use the `image` that is already included in the `md` file for the article.

**Comment by taras** [comment]
@minkimcello can you please add blog page number to the title. Page 1 should just be Blog | Frontside and Blog - page 2 | Frontside for all other pages

**Comment by minkimcello** [comment]
@taras @jorgelainfiesta 

This is what it would look like if we used blog post image for the preview card:

Screen Shot 2020-04-08 at 1 29 27 PM

Is that what we would prefer? Or for marketing purposes would the Frontside logo be better?

And also, is there something about remark (internally) that automatically detects the difference between author and authors? Because some posts use `authors` and some use `author`. When I try to make any changes to the way the markdown fields are queried, it all of a sudden gives me errors for the `author`.

**Comment by jorgelainfiesta** [comment]
Yeah I think that's what we would prefer, because we will be increasing the amount of content that we produce

For example, let's say somebody shares a link to Article A on #random or twitter. Then somebody else, days later, publishes Article B. People don't put a lot of attention, and scroll through things dumped there. If they see Frontside's logo twice, it seem like duplicated content and perhaps not even an article but a corporate page about Frontside rather than content that they'd be interested in.

**Comment by minkimcello** [comment]
@jorgelainfiesta Done and done.

The image of the new logo still has the white specks in the preview cards:

Screen Shot 2020-04-09 at 4 20 32 PM

Do you know why that might be?

**Comment by jorgelainfiesta** [comment]
Excellent Min!

(Interesting that Twitter doesn't support ~Facebook Graph~, I mean 'Open' Graph, but I like their stance somehow.)

**Pull request merged**
